CREATE TABLE rus2000_diff_record (
    Date_YYYYMMDD DATE,
    Symbol VARCHAR(255),
    Action VARCHAR(10),
    INS_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (Date_YYYYMMDD, Symbol)
);
