INSERT INTO yf_stock_info (
    Date_YYYYMMDD,
    symbol,
    maxAge,
    priceHint,
    previousClose,
    open,
    dayLow,
    dayHigh,
    regularMarketPreviousClose,
    regularMarketOpen,
    regularMarketDayLow,
    regularMarketDayHigh,
    payoutRatio,
    beta,
    trailingPE,
    forwardPE,
    volume,
    regularMarketVolume,
    averageVolume,
    averageVolume10days,
    averageDailyVolume10Day,
    bid,
    ask,
    bidSize,
    askSize,
    marketCap,
    fiftyTwoWeekLow,
    fiftyTwoWeekHigh,
    priceToSalesTrailing12Months,
    fiftyDayAverage,
    twoHundredDayAverage,
    trailingAnnualDividendRate,
    trailingAnnualDividendYield,
    currency,
    trailingPegRatio,
    INS_DATE,
    UPD_DATE
)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
ON DUPLICATE KEY UPDATE
    maxAge = VALUES(maxAge),
    priceHint = VALUES(priceHint),
    previousClose = VALUES(previousClose),
    open = VALUES(open),
    dayLow = VALUES(dayLow),
    dayHigh = VALUES(dayHigh),
    regularMarketPreviousClose = VALUES(regularMarketPreviousClose),
    regularMarketOpen = VALUES(regularMarketOpen),
    regularMarketDayLow = VALUES(regularMarketDayLow),
    regularMarketDayHigh = VALUES(regularMarketDayHigh),
    payoutRatio = VALUES(payoutRatio),
    beta = VALUES(beta),
    trailingPE = VALUES(trailingPE),
    forwardPE = VALUES(forwardPE),
    volume = VALUES(volume),
    regularMarketVolume = VALUES(regularMarketVolume),
    averageVolume = VALUES(averageVolume),
    averageVolume10days = VALUES(averageVolume10days),
    averageDailyVolume10Day = VALUES(averageDailyVolume10Day),
    bid = VALUES(bid),
    ask = VALUES(ask),
    bidSize = VALUES(bidSize),
    askSize = VALUES(askSize),
    marketCap = VALUES(marketCap),
    fiftyTwoWeekLow = VALUES(fiftyTwoWeekLow),
    fiftyTwoWeekHigh = VALUES(fiftyTwoWeekHigh),
    priceToSalesTrailing12Months = VALUES(priceToSalesTrailing12Months),
    fiftyDayAverage = VALUES(fiftyDayAverage),
    twoHundredDayAverage = VALUES(twoHundredDayAverage),
    trailingAnnualDividendRate = VALUES(trailingAnnualDividendRate),
    trailingAnnualDividendYield = VALUES(trailingAnnualDividendYield),
    currency = VALUES(currency),
    trailingPegRatio = VALUES(trailingPegRatio),
    UPD_DATE = VALUES(UPD_DATE);
