INSERT INTO yf_financials (
    Date_YYYYMMDD,
    symbol,
    TaxEffectOfUnusualItems,
    TaxRateForCalcs,
    NormalizedEBITDA,
    TotalUnusualItems,
    TotalUnusualItemsExcludingGoodwill,
    NetIncomeFromContinuingOperationNetMinorityInterest,
    ReconciledDepreciation,
    ReconciledCostOfRevenue,
    EBIT,
    NetInterestIncome,
    InterestExpense,
    InterestIncome,
    NormalizedIncome,
    NetIncomeFromContinuingAndDiscontinuedOperation,
    TotalExpenses,
    TotalOperatingIncomeAsReported,
    DilutedAverageShares,
    BasicAverageShares,
    DilutedEPS,
    BasicEPS,
    DilutedNIAvailtoComStockholders,
    NetIncomeCommonStockholders,
    NetIncome,
    NetIncomeIncludingNoncontrollingInterests,
    NetIncomeContinuousOperations,
    TaxProvision,
    PretaxIncome,
    OtherIncomeExpense,
    OtherNonOperatingIncomeExpenses,
    SpecialIncomeCharges,
    OtherSpecialCharges,
    EarningsFromEquityInterest,
    GainOnSaleOfSecurity,
    NetNonOperatingInterestIncomeExpense,
    TotalOtherFinanceCost,
    InterestExpenseNonOperating,
    InterestIncomeNonOperating,
    OperatingIncome,
    OperatingExpense,
    ResearchAndDevelopment,
    SellingGeneralAndAdministration,
    SellingAndMarketingExpense,
    GeneralAndAdministrativeExpense,
    OtherGandA,
    GrossProfit,
    CostOfRevenue,
    TotalRevenue,
    OperatingRevenue,
    INS_DATE,
    UPD_DATE
)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
ON DUPLICATE KEY UPDATE
    TaxEffectOfUnusualItems = VALUES(TaxEffectOfUnusualItems),
    TaxRateForCalcs = VALUES(TaxRateForCalcs),
    NormalizedEBITDA = VALUES(NormalizedEBITDA),
    TotalUnusualItems = VALUES(TotalUnusualItems),
    TotalUnusualItemsExcludingGoodwill = VALUES(TotalUnusualItemsExcludingGoodwill),
    NetIncomeFromContinuingOperationNetMinorityInterest = VALUES(NetIncomeFromContinuingOperationNetMinorityInterest),
    ReconciledDepreciation = VALUES(ReconciledDepreciation),
    ReconciledCostOfRevenue = VALUES(ReconciledCostOfRevenue),
    EBIT = VALUES(EBIT),
    NetInterestIncome = VALUES(NetInterestIncome),
    InterestExpense = VALUES(InterestExpense),
    InterestIncome = VALUES(InterestIncome),
    NormalizedIncome = VALUES(NormalizedIncome),
    NetIncomeFromContinuingAndDiscontinuedOperation = VALUES(NetIncomeFromContinuingAndDiscontinuedOperation),
    TotalExpenses = VALUES(TotalExpenses),
    TotalOperatingIncomeAsReported = VALUES(TotalOperatingIncomeAsReported),
    DilutedAverageShares = VALUES(DilutedAverageShares),
    BasicAverageShares = VALUES(BasicAverageShares),
    DilutedEPS = VALUES(DilutedEPS),
    BasicEPS = VALUES(BasicEPS),
    DilutedNIAvailtoComStockholders = VALUES(DilutedNIAvailtoComStockholders),
    NetIncomeCommonStockholders = VALUES(NetIncomeCommonStockholders),
    NetIncome = VALUES(NetIncome),
    NetIncomeIncludingNoncontrollingInterests = VALUES(NetIncomeIncludingNoncontrollingInterests),
    NetIncomeContinuousOperations = VALUES(NetIncomeContinuousOperations),
    TaxProvision = VALUES(TaxProvision),
    PretaxIncome = VALUES(PretaxIncome),
    OtherIncomeExpense = VALUES(OtherIncomeExpense),
    OtherNonOperatingIncomeExpenses = VALUES(OtherNonOperatingIncomeExpenses),
    SpecialIncomeCharges = VALUES(SpecialIncomeCharges),
    OtherSpecialCharges = VALUES(OtherSpecialCharges),
    EarningsFromEquityInterest = VALUES(EarningsFromEquityInterest),
    GainOnSaleOfSecurity = VALUES(GainOnSaleOfSecurity),
    NetNonOperatingInterestIncomeExpense = VALUES(NetNonOperatingInterestIncomeExpense),
    TotalOtherFinanceCost = VALUES(TotalOtherFinanceCost),
    InterestExpenseNonOperating = VALUES(InterestExpenseNonOperating),
    InterestIncomeNonOperating = VALUES(InterestIncomeNonOperating),
    OperatingIncome = VALUES(OperatingIncome),
    OperatingExpense = VALUES(OperatingExpense),
    ResearchAndDevelopment = VALUES(ResearchAndDevelopment),
    SellingGeneralAndAdministration = VALUES(SellingGeneralAndAdministration),
    SellingAndMarketingExpense = VALUES(SellingAndMarketingExpense),
    GeneralAndAdministrativeExpense = VALUES(GeneralAndAdministrativeExpense),
    OtherGandA = VALUES(OtherGandA),
    GrossProfit = VALUES(GrossProfit),
    CostOfRevenue = VALUES(CostOfRevenue),
    TotalRevenue = VALUES(TotalRevenue),
    OperatingRevenue = VALUES(OperatingRevenue),
    UPD_DATE = VALUES(UPD_DATE);
