INSERT INTO yf_history_metadata (
    Date_YYYYMMDD,
    symbol,
    currency,
    exchangeName,
    instrumentType,
    firstTradeDate,
    regularMarketTime,
    gmtoffset,
    timezone,
    exchangeTimezoneName,
    regularMarketPrice,
    chartPreviousClose,
    priceHint,
    preStart,
    preEnd,
    regularStart,
    regularEnd,
    postStart,
    postEnd,
    dataGranularity,
    validRanges,
    INS_DATE,
    UPD_DATE
)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
ON DUPLICATE KEY UPDATE
    currency = VALUES(currency),
    exchangeName = VALUES(exchangeName),
    instrumentType = VALUES(instrumentType),
    firstTradeDate = VALUES(firstTradeDate),
    regularMarketTime = VALUES(regularMarketTime),
    gmtoffset = VALUES(gmtoffset),
    timezone = VALUES(timezone),
    exchangeTimezoneName = VALUES(exchangeTimezoneName),
    regularMarketPrice = VALUES(regularMarketPrice),
    chartPreviousClose = VALUES(chartPreviousClose),
    priceHint = VALUES(priceHint),
    preStart = VALUES(preStart),
    preEnd = VALUES(preEnd),
    regularStart = VALUES(regularStart),
    regularEnd = VALUES(regularEnd),
    postStart = VALUES(postStart),
    postEnd = VALUES(postEnd),
    dataGranularity = VALUES(dataGranularity),
    validRanges = VALUES(validRanges),
    UPD_DATE = VALUES(UPD_DATE);
