INSERT INTO Trading_History (
  trade_date, 
  settlement_date, 
  ticker, 
  buy_sell_type, 
  No,
  security_name, 
  account, 
  transaction_type, 
  credit_type, 
  settlement_deadline, 
  settlement_currency,
  quantity, 
  unit_price, 
  execution_price, 
  exchange_rate, 
  commission, 
  tax, 
  settlement_amount_usd, 
  settlement_amount_jpy, 
  INS_DATE,
  UPD_DATE
) VALUES ( 
  %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
) ON DUPLICATE KEY UPDATE 
  security_name = VALUES(security_name),
  account = VALUES(account),
  transaction_type = VALUES(transaction_type),
  credit_type = VALUES(credit_type),
  settlement_deadline = VALUES(settlement_deadline),
  settlement_currency = VALUES(settlement_currency),
  quantity = VALUES(quantity),
  unit_price = VALUES(unit_price),
  execution_price = VALUES(execution_price),
  exchange_rate = VALUES(exchange_rate),
  commission = VALUES(commission),
  tax = VALUES(tax),
  settlement_amount_usd = VALUES(settlement_amount_usd),
  settlement_amount_jpy = VALUES(settlement_amount_jpy),
  UPD_DATE = VALUES(UPD_DATE);
